2024-11-30 12:30:57,607 - movie_storage - INFO - New Instance of MovieDB started
2024-11-30 12:30:57,607 - movie_storage - INFO - loading file to local_storage started ...
2024-11-30 12:30:57,608 - movie_storage - INFO - Database loaded into local
2024-11-30 12:30:57,608 - movie_storage - INFO - ... loading file to local_storage finished
2024-11-30 12:30:57,608 - movie_storage - INFO - Context Manager started
2024-11-30 12:30:57,608 - utils - INFO - Printing options menu...
2024-11-30 12:30:57,608 - utils - INFO - ...finished printing options
2024-11-30 12:30:59,261 - movie_storage - ERROR - Exception occurred: unsupported operand type(s) for +: 'dict' and 'int'
Traceback (most recent call last):
  File "/Users/dda/PycharmProjects/MovieMadness/movie_storage.py", line 169, in command_menu_options
    action = int(input("\n\nWhat do you want to do ?   "))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'f'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dda/PycharmProjects/MovieMadness/movies.py", line 6, in main
    app.command_menu_options()
  File "/Users/dda/PycharmProjects/MovieMadness/movie_storage.py", line 171, in command_menu_options
    print(f"invalid option, choose an option between 0 and {len(self.OPTION_LIST +1)}")
                                                                ~~~~~~~~~~~~~~~~~^~
TypeError: unsupported operand type(s) for +: 'dict' and 'int'
2024-11-30 12:30:59,269 - movie_storage - INFO - Saving local storage to file ...
2024-11-30 12:30:59,269 - movie_storage - INFO - Movie DB saved to file: data.json
2024-11-30 12:30:59,270 - movie_storage - INFO - Assertion checked: Remote is synced with Local
2024-11-30 12:30:59,270 - movie_storage - INFO - ... saving local_storage to file finished
2024-11-30 12:30:59,270 - movie_storage - INFO - Context Manager exited. DB saved to: data.json
2024-11-30 12:31:31,952 - movie_storage - INFO - New Instance of MovieDB started
2024-11-30 12:31:31,952 - movie_storage - INFO - loading file to local_storage started ...
2024-11-30 12:31:31,952 - movie_storage - INFO - Database loaded into local
2024-11-30 12:31:31,952 - movie_storage - INFO - ... loading file to local_storage finished
2024-11-30 12:31:31,953 - movie_storage - INFO - Context Manager started
2024-11-30 12:31:31,953 - utils - INFO - Printing options menu...
2024-11-30 12:31:31,953 - utils - INFO - ...finished printing options
2024-11-30 12:31:35,498 - movie_storage - INFO - Option executed List movies by rating
2024-11-30 12:31:35,498 - movie_storage - INFO - starting to sort movies by rating...
2024-11-30 12:31:35,498 - utils - INFO - Printing movies...
2024-11-30 12:31:35,498 - utils - INFO - ...finished printing options
2024-11-30 12:31:35,498 - movie_storage - INFO - ...finished sort movies by rating
2024-11-30 12:31:35,498 - utils - INFO - Printing options menu...
2024-11-30 12:31:35,498 - utils - INFO - ...finished printing options
2024-11-30 12:31:47,166 - movie_storage - ERROR - Exception occurred:
Traceback (most recent call last):
  File "/Users/dda/PycharmProjects/MovieMadness/movies.py", line 6, in main
    app.command_menu_options()
  File "/Users/dda/PycharmProjects/MovieMadness/movie_storage.py", line 169, in command_menu_options
    action = int(input("\n\nWhat do you want to do ?   "))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-11-30 12:31:47,169 - movie_storage - INFO - Saving local storage to file ...
2024-11-30 12:31:47,170 - movie_storage - INFO - Movie DB saved to file: data.json
2024-11-30 12:31:47,170 - movie_storage - INFO - Assertion checked: Remote is synced with Local
2024-11-30 12:31:47,170 - movie_storage - INFO - ... saving local_storage to file finished
2024-11-30 12:31:47,170 - movie_storage - INFO - Context Manager exited. DB saved to: data.json
2024-11-30 12:35:57,155 - movie_storage - INFO - New Instance of MovieDB started
2024-11-30 12:35:57,155 - movie_storage - INFO - loading file to local_storage started ...
2024-11-30 12:35:57,156 - movie_storage - INFO - Database loaded into local
2024-11-30 12:35:57,156 - movie_storage - INFO - ... loading file to local_storage finished
2024-11-30 12:35:57,156 - movie_storage - INFO - Context Manager started
2024-11-30 12:35:57,156 - utils - INFO - Printing options menu...
2024-11-30 12:35:57,156 - utils - INFO - ...finished printing options
2024-11-30 12:36:00,392 - movie_storage - ERROR - Exception occurred: unsupported operand type(s) for +: 'dict' and 'int'
Traceback (most recent call last):
  File "/Users/dda/PycharmProjects/MovieMadness/movie_storage.py", line 169, in command_menu_options
    action = int(input("\n\nWhat do you want to do ?   "))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'f'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/dda/PycharmProjects/MovieMadness/movies.py", line 6, in main
    app.command_menu_options()
  File "/Users/dda/PycharmProjects/MovieMadness/movie_storage.py", line 171, in command_menu_options
    print(f"invalid option, choose an option between 0 and {len(self.OPTION_LIST +1)}")
                                                                ~~~~~~~~~~~~~~~~~^~
TypeError: unsupported operand type(s) for +: 'dict' and 'int'
2024-11-30 12:36:00,397 - movie_storage - INFO - Saving local storage to file ...
2024-11-30 12:36:00,399 - movie_storage - INFO - Movie DB saved to file: data.json
2024-11-30 12:36:00,399 - movie_storage - INFO - Assertion checked: Remote is synced with Local
2024-11-30 12:36:00,399 - movie_storage - INFO - ... saving local_storage to file finished
2024-11-30 12:36:00,399 - movie_storage - INFO - Context Manager exited. DB saved to: data.json
2024-11-30 12:36:22,487 - movie_storage - INFO - New Instance of MovieDB started
2024-11-30 12:36:22,487 - movie_storage - INFO - loading file to local_storage started ...
2024-11-30 12:36:22,488 - movie_storage - INFO - Database loaded into local
2024-11-30 12:36:22,488 - movie_storage - INFO - ... loading file to local_storage finished
2024-11-30 12:36:22,488 - movie_storage - INFO - Context Manager started
2024-11-30 12:36:22,488 - utils - INFO - Printing options menu...
2024-11-30 12:36:22,488 - utils - INFO - ...finished printing options
2024-11-30 12:36:25,181 - movie_storage - ERROR - Ooops. invalid option chosen  invalid literal for int() with base 10: 'fg'
2024-11-30 12:36:25,181 - movie_storage - ERROR - Exception occurred: cannot access local variable 'action' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/dda/PycharmProjects/MovieMadness/movies.py", line 6, in main
    app.command_menu_options()
  File "/Users/dda/PycharmProjects/MovieMadness/movie_storage.py", line 174, in command_menu_options
    if not (isinstance(action, int) and
                       ^^^^^^
UnboundLocalError: cannot access local variable 'action' where it is not associated with a value
2024-11-30 12:36:25,184 - movie_storage - INFO - Saving local storage to file ...
2024-11-30 12:36:25,186 - movie_storage - INFO - Movie DB saved to file: data.json
2024-11-30 12:36:25,186 - movie_storage - INFO - Assertion checked: Remote is synced with Local
2024-11-30 12:36:25,186 - movie_storage - INFO - ... saving local_storage to file finished
2024-11-30 12:36:25,186 - movie_storage - INFO - Context Manager exited. DB saved to: data.json
2024-11-30 12:37:29,359 - movie_storage - INFO - New Instance of MovieDB started
2024-11-30 12:37:29,359 - movie_storage - INFO - loading file to local_storage started ...
2024-11-30 12:37:29,359 - movie_storage - INFO - Database loaded into local
2024-11-30 12:37:29,359 - movie_storage - INFO - ... loading file to local_storage finished
2024-11-30 12:37:29,359 - movie_storage - INFO - Context Manager started
2024-11-30 12:37:29,359 - utils - INFO - Printing options menu...
2024-11-30 12:37:29,359 - utils - INFO - ...finished printing options
2024-11-30 12:37:32,230 - movie_storage - ERROR - Ooops. invalid option chosen  invalid literal for int() with base 10: 'f'
2024-11-30 12:37:32,230 - movie_storage - ERROR - Exception occurred: cannot access local variable 'action' where it is not associated with a value
Traceback (most recent call last):
  File "/Users/dda/PycharmProjects/MovieMadness/movies.py", line 6, in main
    app.command_menu_options()
  File "/Users/dda/PycharmProjects/MovieMadness/movie_storage.py", line 174, in command_menu_options
    if not (isinstance(action, int) and
                       ^^^^^^
UnboundLocalError: cannot access local variable 'action' where it is not associated with a value
2024-11-30 12:37:32,235 - movie_storage - INFO - Saving local storage to file ...
2024-11-30 12:37:32,236 - movie_storage - INFO - Movie DB saved to file: data.json
2024-11-30 12:37:32,236 - movie_storage - INFO - Assertion checked: Remote is synced with Local
2024-11-30 12:37:32,236 - movie_storage - INFO - ... saving local_storage to file finished
2024-11-30 12:37:32,236 - movie_storage - INFO - Context Manager exited. DB saved to: data.json
2024-11-30 12:37:55,475 - movie_storage - INFO - New Instance of MovieDB started
2024-11-30 12:37:55,475 - movie_storage - INFO - loading file to local_storage started ...
2024-11-30 12:37:55,475 - movie_storage - INFO - Database loaded into local
2024-11-30 12:37:55,475 - movie_storage - INFO - ... loading file to local_storage finished
2024-11-30 12:37:55,475 - movie_storage - INFO - Context Manager started
2024-11-30 12:37:55,475 - utils - INFO - Printing options menu...
2024-11-30 12:37:55,475 - utils - INFO - ...finished printing options
2024-11-30 12:37:57,139 - movie_storage - ERROR - Ooops. invalid option chosen  invalid literal for int() with base 10: 'f'
2024-11-30 12:37:57,140 - utils - INFO - Printing options menu...
2024-11-30 12:37:57,140 - utils - INFO - ...finished printing options
2024-11-30 12:38:04,436 - movie_storage - ERROR - Ooops. invalid option chosen  invalid literal for int() with base 10: 'dfd'
2024-11-30 12:38:04,438 - utils - INFO - Printing options menu...
2024-11-30 12:38:04,438 - utils - INFO - ...finished printing options
2024-11-30 12:38:08,097 - utils - INFO - Printing options menu...
2024-11-30 12:38:08,097 - utils - INFO - ...finished printing options
2024-11-30 12:38:22,947 - utils - INFO - Printing options menu...
2024-11-30 12:38:22,948 - utils - INFO - ...finished printing options
2024-11-30 12:38:53,871 - movie_storage - ERROR - Exception occurred:
Traceback (most recent call last):
  File "/Users/dda/PycharmProjects/MovieMadness/movies.py", line 6, in main
    app.command_menu_options()
  File "/Users/dda/PycharmProjects/MovieMadness/movie_storage.py", line 169, in command_menu_options
    action = int(input("\n\nWhat do you want to do ?   "))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-11-30 12:38:53,874 - movie_storage - INFO - Saving local storage to file ...
2024-11-30 12:38:53,875 - movie_storage - INFO - Movie DB saved to file: data.json
2024-11-30 12:38:53,875 - movie_storage - INFO - Assertion checked: Remote is synced with Local
2024-11-30 12:38:53,875 - movie_storage - INFO - ... saving local_storage to file finished
2024-11-30 12:38:53,875 - movie_storage - INFO - Context Manager exited. DB saved to: data.json
2024-11-30 12:38:54,847 - movie_storage - INFO - New Instance of MovieDB started
2024-11-30 12:38:54,847 - movie_storage - INFO - loading file to local_storage started ...
2024-11-30 12:38:54,848 - movie_storage - INFO - Database loaded into local
2024-11-30 12:38:54,848 - movie_storage - INFO - ... loading file to local_storage finished
2024-11-30 12:38:54,848 - movie_storage - INFO - Context Manager started
2024-11-30 12:38:54,848 - utils - INFO - Printing options menu...
2024-11-30 12:38:54,848 - utils - INFO - ...finished printing options
2024-11-30 12:38:58,578 - movie_storage - ERROR - Ooops. invalid option chosen  invalid literal for int() with base 10: 'fr'
2024-11-30 12:38:58,579 - utils - INFO - Printing options menu...
2024-11-30 12:38:58,580 - utils - INFO - ...finished printing options
2024-11-30 12:39:01,191 - movie_storage - INFO - Option executed Print statistics
2024-11-30 12:39:01,191 - movie_storage - INFO - calculating stats started ...
2024-11-30 12:39:01,191 - utils - INFO - Display stats started ...
2024-11-30 12:39:01,191 - utils - INFO - displaying stats: ratings
2024-11-30 12:39:01,192 - utils - INFO - ...Stats printed finished
2024-11-30 12:39:01,192 - movie_storage - INFO - ... Calculating stats finished
2024-11-30 12:39:01,192 - utils - INFO - Printing options menu...
2024-11-30 12:39:01,192 - utils - INFO - ...finished printing options
2024-11-30 12:39:08,618 - movie_storage - INFO - Option executed Filter movies by rating and date
2024-11-30 12:39:08,618 - movie_storage - INFO - Filtering movies started ...
2024-11-30 12:39:08,619 - utils - INFO - Start check movie rating ...
2024-11-30 12:39:10,043 - utils - INFO - No rating for filtering
2024-11-30 12:39:10,043 - utils - INFO - Rating checked for validity 0.0
2024-11-30 12:39:10,044 - utils - INFO - ... Rating check finished
2024-11-30 12:39:10,044 - utils - INFO - Start check movie date ...
2024-11-30 12:39:11,170 - utils - INFO - Filtering using default value 1888
2024-11-30 12:39:11,170 - utils - INFO - Start check movie date ...
2024-11-30 12:39:13,181 - utils - INFO - Filtering using default value 2024
2024-11-30 12:39:13,182 - utils - INFO - Printing movies...
2024-11-30 12:39:13,182 - utils - INFO - ...finished printing options
2024-11-30 12:39:13,182 - utils - INFO - Printing options menu...
2024-11-30 12:39:13,182 - utils - INFO - ...finished printing options
2024-11-30 12:39:20,152 - movie_storage - ERROR - Exception occurred:
Traceback (most recent call last):
  File "/Users/dda/PycharmProjects/MovieMadness/movies.py", line 6, in main
    app.command_menu_options()
  File "/Users/dda/PycharmProjects/MovieMadness/movie_storage.py", line 169, in command_menu_options
    action = int(input("\n\nWhat do you want to do ?   "))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
2024-11-30 12:39:20,155 - movie_storage - INFO - Saving local storage to file ...
2024-11-30 12:39:20,155 - movie_storage - INFO - Movie DB saved to file: data.json
2024-11-30 12:39:20,155 - movie_storage - INFO - Assertion checked: Remote is synced with Local
2024-11-30 12:39:20,155 - movie_storage - INFO - ... saving local_storage to file finished
2024-11-30 12:39:20,155 - movie_storage - INFO - Context Manager exited. DB saved to: data.json
